### ISSUE TITLE
[Bug]: Rainbow delimiters no longer working for C# files

### ISSUE THREAD

**Issue by KettLovahr** [HiPhish/rainbow-delimiters.nvim#112]
### Neovim version

v0.10.0-dev-3117+g4e5c633ed

### Language affected

c_sharp

### Query

rainbow-delimiters

### Strategy

global

### Description

The rainbow effect for delimiters in C# is no longer working. This might've happened with a recent update, but I have been unable to track down which commit might be the culprit.

This can be seen with the provided test files, here is `loop.cs`
![image](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/25535207/f79b0929-9945-404f-9da7-1295948848e5)

I have ensured treesitter is working, I have also run `:TSUpdate` to ensure the parsers are all up to date. No other file type seems to be affected.

**Comment by HiPhish** [comment]
Probably a change in node names in the C# parser. I'm currently out of town, feel free to ping me if I don't reply in two weeks time.

**Comment by KettLovahr** [comment]
Yeah, it's working now! Thank you! ^-^

**Comment by FlawlessCasual17** [comment]
Hey @HiPhish, I am experiencing this problem just like the author of this issue. I am using the latest version of your plugin, and I do not see any rainbow effect for delimiters (such as the brackets). Is CSharp no longer supported?

![Image](https://github.com/user-attachments/assets/28c31af2-f182-4b76-993c-fc5dd2baf78b)

**Comment by HiPhish** [comment]
It's working for me. I'll try updating the parser, maybe they have changed the names of nodes again.

**Comment by HiPhish** [comment]
Nope, still works fine. What is your configuration? Do you have the `c_sharp` parser installed?

![Image](https://github.com/user-attachments/assets/770f34d8-d9d6-4689-b339-5393521b3821)

**Comment by FlawlessCasual17** [comment]
How do I install this `c_sharp` parser?

**Comment by HiPhish** [comment]
Try the command `:TSInstall c_sharp`. I don't know about LazyVim, but I would guess that it has [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) included. Neovim has Tree-sitter support built-in, but you still need a parser for every language you want to use it with. Technically you don't need to install parsers with `:TSInstall`, you can install them manually, but nvim-treesitter is the easiest "out of the box" way.
