### ISSUE TITLE
Use LanguageTree:children() instead of the deprecated LanguageTree:for_each_child()

### ISSUE THREAD

**Issue by fraidev** [HiPhish/rainbow-delimiters.nvim#113]
### Neovim version

 ```
 $ nvim --version
NVIM v0.10.0-dev-3122+ga0a189a8e
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Language affected

Tested with Rust and Lua.

### Description

Got this error: 

```
LanguageTree:for_each_child() is deprecated, use LanguageTree:children() instead. :help deprecated Feature will be removed in Nvim 0.11
```

**Comment by fraidev** [comment]
Sorry, I was using the old plugin

**Comment by realth000** [comment]
> @realth000 The commit you have installed is indeed the latest commit, but the error message does not match. Line 118 of `lua/rainbow-delimiters/strategy/global.lua` is a comment. Are you sure your package manager has actually downloaded the correct version?
> 
> https://github.com/HiPhish/rainbow-delimiters.nvim/blob/master/lua/rainbow-delimiters/strategy/global.lua#L118

My fault, my config migrated from `packer` to `lazy` several months ago but i forget to delete downloaded plugins in `~/.local/share/nvim/site/packer`. This error was fixed after I delete the legacy cache. Thanks!
