### ISSUE TITLE
[Bug]: New Vue Language Server seems to impact the plugin parser

### ISSUE THREAD

**Issue by barnacker** [HiPhish/rainbow-delimiters.nvim#136]
### Neovim version

0.10.1

### Description

This used to work fine, now Volar / Vue Language Server has a new integration with typescript-tools, I thinks this is messing up something in the tree...

See behavior:

https://github.com/user-attachments/assets/f44a31ea-1ac1-450f-ace0-0196c2934e97

**Comment by HiPhish** [comment]
I don't use Vue, so I'm just taking a guess here. It looks like semantic tokens are overwriting rainbow delimiters. By default semantic tokens have a priority of 125 (see `:h vim.highlight.priorities`) and rainbow delimiters have a priority of 110. You can adjust the priority in your settings, see `:h g:rainbow_delimiters`.

```vim
g:rainbow_delimiters = {
    \ 'priority': {'vue': 130}
\ }
```

```lua
vim.g.rainbow_delimiters = {
    priority = {vue = 130}
}
```

**Comment by barnacker** [comment]
SOLVED!

**Comment by barnacker** [comment]
SOLVED!
