### ISSUE TITLE
[Bug]: rainbow-delimiters plugin not working with go language

### ISSUE THREAD

**Issue by ekamidi** [HiPhish/rainbow-delimiters.nvim#142]
### Neovim version

0.9.5

### Language affected

Go

### Description

I have installed rainbow-delimiters plugin with the default configuration.
After restarting my neovim and testing, the plugin is working for Lua, python, javascript, html, xml files BUT not for go language files.

**Comment by ekamidi** [comment]
I have upgraded my neovim to version v0.10.2 and it fixed the issue with go language. We can close this issue now.
nvim -v
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1-v" for more info

**Comment by Facegrinder** [comment]
@ekamidi How did you get it working with Go?
For me it works in Lua/JS/TS, but not with Go, same Neovim version as you stated.
