### ISSUE TITLE
[Bug]: Doesn't works with .tsx files

### ISSUE THREAD

**Issue by t1gu1** [HiPhish/rainbow-delimiters.nvim#18]
### Neovim version

0.9.1

### Language affected

tsx

### Description

```Text
const GodScreen: FC = () => {
  const test = {
    a: {
      b: {
        c: {
          d: {
            e: {
              f: {
                g: {
                  h: {},
                },
              },
            },
          },
        },
      },
    },
  };

  return <></>;
};

export default GodScreen;
```

**Comment by t1gu1** [comment]
I test other files extensions.

It doesn't works also for
- `.jsx`
- `.js`

But it works fine if it's a `.ts`

**Comment by schardev** [comment]
Possibly duplicate of #14

**Comment by HiPhish** [comment]
Please try the current `master` branch.

> But it works fine if it's a `.ts`

Yes, because the TypeScript grammar does not not include React support. The Javascript grammar does include React support, whether you need it or not.

**Comment by t1gu1** [comment]
Works since the update! :D
Thanks!
