### ISSUE TITLE
API to toggle rainbow

### ISSUE THREAD

**Issue by mystilleef** [HiPhish/rainbow-delimiters.nvim#27]
### Neovim version

master

### Description

```Text
Can you provide an API to explicitly toggle Rainbow? I like to disable colors in insert mode.
```

**Comment by HiPhish** [comment]
What would you want this API to be like? Since you want to disable and enable it when changing modes how about three functions like this?

```lua
-- Disable rainbow for buffer (bufnr or 0 for current buffer)
rainbow_delimiters.disable(buffnr)

-- Enable rainbow again for buffer (bufnr or 0 for current buffer)
rainbow_delimiters.enable(buffnr)

-- Toggle rainbow for buffer (bufnr or 0 for current buffer)
rainbow_delimiters.enable(buffnr)
```

You could then call these functions in an autocommand for `InsertEnter` and `InsertLeave`.

**Comment by mystilleef** [comment]
```
-- Toggle rainbow for buffer (bufnr or 0 for current buffer)
rainbow_delimiters.enable(buffnr)
```

I assume you meant to write `rainbow_delimiters.toggle(bufnr)` and not `enable`. `enable` should not `toggle` to avoid confusion.

**Comment by HiPhish** [comment]
Try out the current `master`; the functions are implemented now. And yes, that was a typo, I meant of `toggle` of course.

**Comment by mystilleef** [comment]
Great work! 

There's only 1 issue. Passing nothing to the APIs should automatically use the current buffer. 

As it stands you're forced to pass a buffer number to the APIs which shouldn't be necessary. Public APIs in general should be `nil` friendly.

Other than that after my 10 minutes of testing, it seems to work well.

Thank you!

**Comment by HiPhish** [comment]
I have made them `nil`-tolerant. I don't think that is a general think across Neovim functions, but on the other hand it barely adds any code, so went through with it anyway.
