### ISSUE TITLE
[Bug]: java rainbow highlighting not working

### ISSUE THREAD

**Issue by jay-babu** [HiPhish/rainbow-delimiters.nvim#31]
### Neovim version

0.9.1

### Language affected

Java

### Description

```Text
package com.transformity.pos.util;

import java.math.BigDecimal;
import java.math.RoundingMode;

public class Utils {
  public static String toUpperCamelCase(String input) {
    String[] words = input.split("\\s+");
    StringBuilder result = new StringBuilder();
    for (String word : words) {
      if (!word.isEmpty()) {
        String capitalizedWord =
            word.substring(0, 1).toUpperCase() + word.substring(1).toLowerCase();
        result.append(capitalizedWord);
      }
    }
    return result.toString();
  }

  public static BigDecimal calculateProfitMargin(BigDecimal sellPrice, BigDecimal buyPrice) {
    if (sellPrice == null || buyPrice == null) {
      return null;
    }
    try {
      return ((sellPrice.subtract(buyPrice)).divide(buyPrice, RoundingMode.HALF_UP))
          .multiply(BigDecimal.valueOf(100));
    } catch (ArithmeticException e) {
      return null;
    }
  }

  public static int calculateBuyRangeImportance(String buyRange) {
    if (buyRange == null) {
      return -1;
    }
    return switch (buyRange) {
      case "PRICE INCREASE" -> 100;
      case "BUY 30", "BUY 60", "BUY 90", "BUY 120", "BUY 150" -> 90;
      default -> 0;
    };
  }
}
```

**Comment by jay-babu** [comment]
![alacritty_My723eFkBs](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/36803168/e19a7a54-91eb-42de-b11e-85deca4b248a)

**Comment by HiPhish** [comment]
Works for me. Do you have the Tree-sitter grammar installed? What does `checkhealth rainbow-delimiters` display?

![Screenshot_20230823_185139](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/4954650/ec36ea8d-e9b0-4850-ba69-7bfc11116716)

**Comment by jay-babu** [comment]
```
==============================================================================
rainbow-delimiters: require("rainbow-delimiters.health").check()

- ERROR The healthcheck report for "rainbow-delimiters" plugin is empty.
```

**Comment by HiPhish** [comment]
Looks like the plugin did not install properly for you. Can you please try uninstalling and installing it again? If that does not work, can you please post the directory contents of your local copy? You can use the `tree` command to print a nice directory tree.

**Comment by jay-babu** [comment]
https://gist.github.com/jay-babu/787c7376f0b058f1ca51c26df4a5bc1d. I uninstalled and installed and the same error came up again

**Comment by HiPhish** [comment]
That's weird. Which version of Neovim are you running? Are you somehow lazy-loading this plugin?

**Comment by jay-babu** [comment]
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I was lazy loading, but just tried without it. the same problem

**Comment by jay-babu** [comment]
I am using the lazy plugin manager

**Comment by HiPhish** [comment]
Does the problem still persist on the current `master`? Are languages other
than Java affected? If you `:edit` the buffer again does it work then?

As for the health check, we can compare hash values. Here is the SHA-256 of my
file:

```
5e78ec80c7c62699d0309bc646142922ed1e24224fcfd5a8eeb0866a80ab5a01  lua/rainbow-delimiters/health.lua
```

If yours differs then there is something wrong with your file.
