### ISSUE TITLE
[Bug]: Don't work on python files

### ISSUE THREAD

**Issue by kobzar** [HiPhish/rainbow-delimiters.nvim#41]
### Neovim version

NVIM v0.9.2

### Language affected

Python

### Description

```Text
This plugin work normaly with lua files but doesnt work in python

I am use AstroNvim with this configuration
https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/editing-support/nvim-ts-rainbow2/init.lua

My Theme is Material (as i say before in Lua file all is good)

```
![image](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/1912842/3a556ff1-0948-4d20-9af1-ec8ff85f0053)

**Comment by kobzar** [comment]
![image](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/1912842/25d3fd69-7458-4483-82fb-9455036de4e7)

**Comment by HiPhish** [comment]
Do you have the Python parser installed? Execute `:TSInstallInfo` and the Python entry. If it is not installed you can add it via `:TSInstall python`. If that does not help execute `:checkhealth rainbow-delimiters` to validate your configuration.

**Comment by kobzar** [comment]
TS python is instaled
checkhealth rainbow-delimiters command return 
```
rainbow-delimiters: require("rainbow-delimiters.health").check()

- ERROR The healthcheck report for "rainbow-delimiters" plugin is empty.
```

But in the same time lua file
<img width="477" alt="image" src="https://github.com/HiPhish/rainbow-delimiters.nvim/assets/1912842/637be8ce-cbba-49ee-8d80-42ba773cbd02">

**Comment by kobzar** [comment]
Just change my config to 
```lua
  {
    "HiPhish/rainbow-delimiters.nvim",
    dependencies = "nvim-treesitter/nvim-treesitter",
    event = "VeryLazy",
    config = function(_, opts) require "rainbow-delimiters.setup"(opts) end,
  },
```
And now its look normal
