### ISSUE TITLE
[Enhancement]: Exempt HTML tags from highlighting in JSX/TSX

### ISSUE THREAD

**Issue by nanyaDev** [HiPhish/rainbow-delimiters.nvim#6]
I would like to recreate the behaviour of VSCode's bracket pair colorization for `jsx/tsx` files, where the `HTML` tags are exempt from highlighting, as you can see below:

<img width="454" alt="image" src="https://github.com/HiPhish/rainbow-delimiters.nvim/assets/40901142/3b40accf-7798-4dd4-81fc-8215edaf0e49" /><br/>

Is there any way to achieve this using a custom strategy or query?

**Comment by nanyaDev** [comment]
**Update**: I was able to achieve this using a custom `nvim-treesitter` query:

```scm
; ~/.config/nvim/after/queries/tsx/highlights.scm

;; extends

[
 (jsx_element
   open_tag: (jsx_opening_element
               name: (identifier) @tag.component.jsx
               (#lua-match? @tag.component.jsx "^[A-Z]")
               (#set! "priority" 999)))
 (jsx_element
   close_tag: (jsx_closing_element
               name: (identifier) @tag.component.jsx
               (#lua-match? @tag.component.jsx "^[A-Z]")
               (#set! "priority" 999)))
 (jsx_self_closing_element
   name: (identifier) @tag.component.jsx
   (#lua-match? @tag.component.jsx "^[A-Z]")
   (#set! "priority" 999))
]
```

I figured this out using code from https://github.com/oxfist/night-owl.nvim.

**Comment by HiPhish** [comment]
You can now set `rainbow-parens` as the query for Javascript (and JSX) and TSX
in your settings.

```vim
let g:rainbow_delimiters = {
    \ 'query': {
        \ 'javascript': 'rainbow-parens',
        \ 'tsx': 'rainbow-parens',
    \}
\}
```

```lua
vim.g.rainbow_delimiters = {
    query = {
        javascript = 'rainbow-parens',
        tsx = 'rainbow-parens',
    }
}
```
