### ISSUE TITLE
[Question]: highlights do not keep when fold text

### ISSUE THREAD

**Issue by gh-liu** [HiPhish/rainbow-delimiters.nvim#71]
when use `vim.treesitter.foldtext()` to show the fold text, the highlights of `rainbow-delimiters.nvim` do not show, is there a way to fix this?

```lua
vim.o.foldmethod = "expr"
vim.o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.o.foldtext = "v:lua.vim.treesitter.foldtext()"[
```

<img width="395" alt="Snipaste_2023-11-30_16-36-07" src="https://github.com/HiPhish/rainbow-delimiters.nvim/assets/46311996/ab2a7ee2-68cc-46cc-8e4f-1ffffa3ce3c9">

**Comment by HiPhish** [comment]
I don't know if this is possible. This requires some way of preserving extmarks in the replacement text and letting them "shine through" to the surface. I will need to look into how the highlighting is preserved in Treesitter. Maybe it can be done, maybe not.

**Comment by Danielkonge** [comment]
This seems to be worked on upstream. You can check the progress here: https://github.com/neovim/neovim/pull/20750

When that is merged, you will get the folding you are asking for (from what I understand).

**Comment by gh-liu** [comment]
> This seems to be worked on upstream. You can check the progress here: [neovim/neovim#20750](https://github.com/neovim/neovim/pull/20750)
> 
> When that is merged, you will get the folding you are asking for (from what I understand).

Thanks
