### ISSUE TITLE
[Bug]: Possible regression, can't implement whitelist only rainbow delimiters

### ISSUE THREAD

**Issue by davidsierradz** [HiPhish/rainbow-delimiters.nvim#8]
### Neovim version

nightly

### Description

Hi, before commit bc1e12be89d46190f4ca798e10a9203d90248b22, I could implement a whitelist only setup enabled with a defined set of languages:

```lua
local rainbow_delimiters = require('rainbow-delimiters')
                                                         
vim.g.rainbow_delimiters = {
  strategy = {
    [''] = rainbow_delimiters.strategy['noop'],
    clojure = rainbow_delimiters.strategy['global'],
    fennel = rainbow_delimiters.strategy['global'],
    commonlisp = rainbow_delimiters.strategy['global'],
    query = rainbow_delimiters.strategy['global'],
    janet = rainbow_delimiters.strategy['global'],
    racket = rainbow_delimiters.strategy['global'],
    scheme = rainbow_delimiters.strategy['global'],
  },
  highlight = {
    '@rainbow.1',
    '@rainbow.2',
    '@rainbow.3',
    '@rainbow.4',
    '@rainbow.5',
    '@rainbow.6',
  },
}
```

Basically, I want to enable rainbow delimiters only on lisp-like languages, is this use-case valid?

Thanks

**Comment by HiPhish** [comment]
Does setting the strategy to `noop` not work?

> Basically, I want to enable rainbow delimiters only on lisp-like languages, is this use-case valid?

That does sound like a reasonable thing to want to do. I think having an explicit whitelist and blacklist in the settings would be better, otherwise I have to run a bunch of logic and waste resources just to set up a bunch of machinery that does nothing.

**Comment by davidsierradz** [comment]
> Does setting the strategy to noop not work?

Yeah, after commit bc1e12be89d46190f4ca798e10a9203d90248b22:

![image](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/9190258/b82814e8-dde5-4768-b401-58f3a679299c)

Before (5a074244a40f9e2e0ba219268c69cb256ce16696):

![image](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/9190258/bd22a992-a7e7-4892-95a8-9857be59f6bd)

Same config:

```lua
local rainbow_delimiters = require('rainbow-delimiters')
                                                        
vim.g.rainbow_delimiters = {                            
  strategy = {                                          
    [''] = rainbow_delimiters.strategy['noop'],         
    clojure = rainbow_delimiters.strategy['global'],    
    fennel = rainbow_delimiters.strategy['global'],     
    commonlisp = rainbow_delimiters.strategy['global'], 
    query = rainbow_delimiters.strategy['global'],      
    janet = rainbow_delimiters.strategy['global'],      
    racket = rainbow_delimiters.strategy['global'],     
    scheme = rainbow_delimiters.strategy['global'],     
  },                                                    
  highlight = {                                         
    '@rainbow.1',                                       
    '@rainbow.2',                                       
    '@rainbow.3',                                       
    '@rainbow.4',                                       
    '@rainbow.5',                                       
    '@rainbow.6',                                       
  },                                                    
}                                                       
```

**Comment by HiPhish** [comment]
The fallback setting should work now again. Please try out the latest `master`.
I still want to implement white- and blacklist eventually, but this should work
in the meantime.

**Comment by davidsierradz** [comment]
Thanks! Confirming that it works again!

**Comment by HiPhish** [comment]
FYI, white- and blacklisting is implemented now. You can add an explicit list of languages for which you want rainbow delimiters enabled:

```lua
vim.g.rainbow_delimiters = {
    -- ... your configuration
    whitelist = {'commonlisp', 'clojure', 'scheme', 'fennel', 'janet', 'racket'}
}
```

This will abort the machinery much earlier than if you set `noop` as your strategy.
