### ISSUE TITLE
[Bug] With tsx, highlighting of delimiters is inconsistent when trying to include attribute names

### ISSUE THREAD

**Issue by noomly** [HiPhish/rainbow-delimiters.nvim#88]
The current tsx query (at [queries/tsx/rainbow-delimiters.scm](https://github.com/HiPhish/rainbow-delimiters.nvim/blob/master/queries/tsx/rainbow-delimiters.scm)) works correctly but is only highlights tags, as illustrated here:
 ![2024_01_17-16_06_21_904549567](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/9301991/00e6cc3f-9bdd-41fb-93c4-24ee41a560df)

I would like it to highlight the attributes names as well. I've tried modifying the query linked above to do this, and came up with:

```scm
; inherits: typescript

(jsx_element
  open_tag: (jsx_opening_element
              "<" @delimiter
              name: (identifier) @delimiter
              attribute: (jsx_attribute
                           (property_identifier) @delimiter)?
              ">" @delimiter)
  close_tag: (jsx_closing_element
               "</" @delimiter
               name: (identifier) @delimiter
               ">" @delimiter @sentinel)) @container

(jsx_element
  open_tag: (jsx_opening_element
              "<" @delimiter
              name: (member_expression) @delimiter
              attribute: (jsx_attribute
                           (property_identifier) @delimiter)?
              ">" @delimiter)
  close_tag: (jsx_closing_element
              "</" @delimiter
               name: (member_expression) @delimiter
              ">" @delimiter @sentinel)) @container

(jsx_self_closing_element
  "<" @delimiter
  name: (identifier) @delimiter
  attribute: (jsx_attribute
               (property_identifier) @delimiter)?
  "/>" @delimiter @sentinel) @container


(jsx_self_closing_element
  "<" @delimiter
  name: (member_expression) @delimiter
  attribute: (jsx_attribute
               (property_identifier) @delimiter)?
  "/>" @delimiter @sentinel) @container

(jsx_expression
  "{" @delimiter
  "}" @delimiter @sentinel) @container
```

Which produces the following result:
![2024_01_17-16_07_02_961896557](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/9301991/4bb2963b-296a-4be3-b111-49f95ab8b220)

It does include the attribute tags in the highlighting but it now has some inconsistencies. For example, you can see in the screenshot that for the element `Text.h1`, the opening bracket of the opening tag and the closing bracket of the closing tag are inconsistent with the color of the rest of the element. Is there something wrong with my query or is this a bug with rainbow-delimiters?

I'm using Neovim v0.9.4.

**Comment by HiPhish** [comment]
Your pattern is too complicated. Since you want to highlight the entire opening and closing tag you can capture the entire thing.

```
(jsx_element
  (jsx_opening_element) @delimiter
  (jsx_closing_element) @delimiter @sentinel) @container
```

**Comment by noomly** [comment]
Thank you for taking a look!

However I do not wish to loose syntax highlighting on the attribute values as it would hurt readability. I specifically want to include the attribute names in the capture, I can't really see how to make the capture "less complicated" with that in mind. By the way, it isn't much more complicated than the default query I linked. It only adds the following:
```scm
attribute: (jsx_attribute
             (property_identifier) @delimiter)?
```
To a few statements, which doesn't seem excessive when compared to the original query?

I'm not familiar with the plugin's internals at all so I can't really tell where the inconsistencies I'm seeing are coming from. Is it an issue with the way I wrote the query? Or Is rainbow-delimiters currently unable to reliably highlight captures in a single color once they reach a certain degree of complexity?

**Comment by HiPhish** [comment]
> The issue with your solution is that I'd like to keep the syntax highlighting on the attribute values... I specifically want to only include the attribute names in the capture

Sorry, I misunderstood you then. In that case @Danielkonge is correction, you need to use the `*` quantifier instead of `?`. It works similar to regular expressions in that Tree-sitter will never match too few or too many nodes, but exactly as many as you specify. Here is what it looks like for me:

![Screenshot_20240121_190842](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/4954650/1df15eb0-d728-45e2-98dc-9d27fbcde8a6)

Notice how `style`, `class` and `foo` all have the same colour as the tag name.

**Comment by noomly** [comment]
This works exactly as expected, thank you both. And many thanks for your work on the plugin!
